### ISSUE TITLE
Todo: Some optimization

### ISSUE THREAD

**Issue by HerringtonDarkholme** [HerringtonDarkholme/kilimanjaro#1]
- [x] optimize memory usage by caching dipatch and commit
- [x] pass store.getters to raw getter function
- [x] forbid access this by specifying `this: void` in function
- [x] add type bound to Opt and Store

**Comment by HerringtonDarkholme** [comment]
Bonus: implementation and interface are separated!
